=== LRSORRENTI/XML-Python/XML/01_Intro/02_Student.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="class">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="student" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="firstname" type="xs:string" />
                            <xs:element name="lastname" type="xs:string" />
                            <xs:element name="age" type="xs:integer" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="subject" type="xs:string" />
                <xs:element name="hour" type="xs:integer" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== LRSORRENTI/XML-Python/XML/01_Intro/updated_xml_file.xml
<class xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="02_Student.xsd">
    <student>
        <firstname>
           Alex 
        </firstname>
        <lastname>
            Bell
        </lastname>
        <age>
            20
        </age>
    </student>
    <student>
        <firstname>Martin</firstname>
        <lastname>
            Rockwell
        </lastname>
        <age>
            19
        </age>
    </student>
    <student>
        <firstname>
           Stephen
        </firstname>
        <lastname>
            Gort
        </lastname>
        <age>
            22
        </age>
    </student>
    <subject>
        Mathematics
    </subject>
    <hour>10</hour>
</class>
